/*
    This file is generated by ChatGPT 5.2 for compare between different AI models and stategy to play BattleShipGame
*/
#pragma once
#include "bot_base.h"
#include "board.h"

#include <random>
#include <vector>
#include <deque>

class BotGpt : public PlayerBotBase {
public:
    BotGpt(std::shared_ptr<GameSession::IGamePlayerAction> action_interface,
                  PlayerType player_type);

    RequestId placeShip(Board::ShipType ship_type) override;
    RequestId makeShot() override;

    void onPlayerShotResult(const Board::Position& position,
                            bool is_hit,
                            bool is_ship_sunk) override;

private:
    enum class Cell : uint8_t { Unknown, Miss, Hit, Sunk };

    std::random_device rd_;
    std::mt19937 gen_;

    std::vector<std::vector<Cell>> enemy_;     // our knowledge of opponent
    std::vector<int> remaining_lengths_;       // remaining enemy ship sizes (e.g. 1,1,1,1,2,2,2,3,3,4)

    // --- shooting helpers
    Board::Position bestHeatmapShot();
    bool placementConsistent(int r, int c, bool horizontal, int L,
                             const std::vector<Board::Position>& targetCluster) const;

    bool isValidTarget(const Board::Position& pos) const;
    Board::Position randomPosition();

    // --- hit cluster helpers (targeting / sunk detection)
    std::vector<std::vector<bool>> visitedMask() const;
    std::vector<Board::Position> collectHitClusterFrom(const Board::Position& start) const;
    std::vector<std::vector<Board::Position>> getAllHitClusters() const;
    std::vector<Board::Position> chooseTargetCluster() const;

    void markWaterAroundSunkCluster(const std::vector<Board::Position>& cluster);
    void removeSunkLength(int len);

    // --- placement helpers
    int shipPlacementScore(Board::Position pos, bool horizontal, size_t L) const;

    static int edgeDist(int r, int c);

    void initRemainingShipsFromBoardRules();
};
