// /*
//     This file is generated by Claude Opus 4.5 for compare between different AI models and stategy to play BattleShipGame
// */
// // bot_hunter.h
// #pragma once

// #include "bot_base.h"
// #include "board.h"
// #include <random>
// #include <deque>
// #include <vector>
// #include <algorithm>

// class BotSonnet : public PlayerBotBase {
// public:
//     BotSonnet(std::shared_ptr<GameSession::IGamePlayerAction> action_interface,
//                   PlayerType player_type);

//     RequestId placeShip(Board::ShipType ship_type) override;
//     RequestId makeShot() override;
//     void onPlayerShotResult(const Board::Position& position,
//                            bool is_hit,
//                            bool is_ship_sunk) override;

// private:
//     enum class Mode { Hunt, Target };
//     enum class CellState { Unknown, Miss, Hit };

//     // Random generation
//     std::random_device rd_;
//     mutable std::mt19937 gen_;

//     // Board state tracking
//     std::vector<std::vector<bool>> tried_;
//     std::vector<std::vector<CellState>> cell_states_;

//     // Targeting state
//     Mode mode_ = Mode::Hunt;
//     std::deque<Board::Position> target_queue_;
//     std::vector<Board::Position> current_hit_chain_;

//     // Ship tracking - stores sizes of remaining enemy ships
//     std::vector<size_t> remaining_ship_sizes_;

//     // For placement strategy - tracks cells occupied by our ships
//     std::vector<Board::Position> placed_ship_cells_;

//     // Core methods
//     Board::Position randomPosition() const;
//     bool isValidTarget(const Board::Position& pos) const;
//     void onHit(const Board::Position& pos);
//     void onShipSunk();
//     void enqueueNeighbors(const Board::Position& pos);

//     // Probability-based hunting
//     Board::Position findBestHuntTarget();
//     std::vector<std::vector<double>> calculateProbabilityMap() const;
//     bool canShipFitAt(const Board::Position& start, size_t size, bool is_vertical) const;

//     // Intelligent targeting
//     void prioritizeTargetQueue();
//     void filterTargetQueueByOrientation();
//     std::pair<bool, bool> detectHitOrientation() const;

//     // Intelligent placement
//     Board::Position findBestPlacement(Board::ShipType ship_type, bool& is_vertical);
//     double evaluatePlacementPosition(const Board::Position& pos, size_t ship_size,
//                                      bool is_vertical) const;

//     // Initialize remaining ships based on game rules
//     void initializeRemainingShips();
// };
