/*
    This file is generated by Claude Opus 4.5 for compare between different AI models and stategy to play BattleShipGame
*/
// bot_sonnet.cpp
#include "bot_sonnet.h"
#include <algorithm>
#include <cmath>
#include <numeric>
#include <limits>

BotSonnet::BotSonnet(
    std::shared_ptr<GameSession::IGamePlayerAction> action_interface,
    const PlayerType player_type)
    : PlayerBotBase(action_interface, player_type),
      gen_(rd_()) {
    LOG_V("Create a smart bot with probability-based targeting by Sonnet Opus 4.5");

    tried_.resize(Board::kBoardSizeRow,
                  std::vector<bool>(Board::kBoardSizeCol, false));
    cell_states_.resize(Board::kBoardSizeRow,
                        std::vector<CellState>(Board::kBoardSizeCol, CellState::Unknown));

    initializeRemainingShips();
}

void BotSonnet::initializeRemainingShips() {
    remaining_ship_sizes_.clear();

    // Add all ships based on board.h definitions
    // Iterate through all ship types
    for (size_t i = 0; i < Board::kNumberOfShips; ++i) {
        auto ship_type = static_cast<Board::ShipType>(i);
        size_t count = Board::get_max_ship_count(ship_type);
        size_t size = Board::get_ship_size(ship_type);

        for (size_t j = 0; j < count; ++j) {
            remaining_ship_sizes_.push_back(size);
        }
    }

    // Result: 4x size-1 (Destroyers), 3x size-2 (Submarines),
    //         2x size-3 (Cruisers), 1x size-4 (Battleship)
    // Total: 10 ships

    LOG_V("Initialized {} enemy ships to track", remaining_ship_sizes_.size());
}

// =============================================================================
// INTELLIGENT SHIP PLACEMENT
// =============================================================================

RequestId BotSonnet::placeShip(const Board::ShipType ship_type) {
    bool is_vertical;
    Board::Position pos = findBestPlacement(ship_type, is_vertical);

    // Track placed cells for future placement decisions
    size_t size = Board::get_ship_size(ship_type);
    for (size_t i = 0; i < size; ++i) {
        int r = is_vertical ? pos.first + static_cast<int>(i) : pos.first;
        int c = is_vertical ? pos.second : pos.second + static_cast<int>(i);
        placed_ship_cells_.push_back({r, c});
    }

    // Note: action_interface->placeShip uses 'horizontal' parameter
    // horizontal = !is_vertical
    return action_interface_->placeShip(ship_type, pos, !is_vertical);
}

Board::Position BotSonnet::findBestPlacement(const Board::ShipType ship_type,
                                                  bool& is_vertical) {
    size_t ship_size = Board::get_ship_size(ship_type);

    struct PlacementCandidate {
        Board::Position pos;
        bool is_vertical;
        double score;
    };

    std::vector<PlacementCandidate> candidates;

    // Evaluate all possible placements
    for (size_t r = 0; r < Board::kBoardSizeRow; ++r) {
        for (size_t c = 0; c < Board::kBoardSizeCol; ++c) {
            Board::Position pos{static_cast<int>(r), static_cast<int>(c)};

            // Try vertical placement (is_vertical = true)
            if (Board::Board::is_possible_to_place_ship(board_, pos, ship_type, true)) {
                double score = evaluatePlacementPosition(pos, ship_size, true);
                candidates.push_back({pos, true, score});
            }

            // Try horizontal placement (is_vertical = false)
            if (Board::Board::is_possible_to_place_ship(board_, pos, ship_type, false)) {
                double score = evaluatePlacementPosition(pos, ship_size, false);
                candidates.push_back({pos, false, score});
            }
        }
    }

    if (candidates.empty()) {
        // Fallback to random placement
        std::uniform_int_distribution<> row(0, Board::kBoardSizeRow - 1);
        std::uniform_int_distribution<> col(0, Board::kBoardSizeCol - 1);
        std::uniform_int_distribution<> rot(0, 1);

        Board::Position pos;
        do {
            pos = {row(gen_), col(gen_)};
            is_vertical = rot(gen_);
        } while (!Board::Board::is_possible_to_place_ship(
            board_, pos, ship_type, is_vertical));
        return pos;
    }

    // Sort by score (higher is better)
    std::sort(candidates.begin(), candidates.end(),
        [](const auto& a, const auto& b) { return a.score > b.score; });

    // Pick from top candidates with randomness to avoid predictability
    size_t top_n = std::min(candidates.size(), static_cast<size_t>(10));

    // Weight selection toward higher scores
    std::vector<double> weights;
    for (size_t i = 0; i < top_n; ++i) {
        weights.push_back(std::pow(0.6, static_cast<double>(i)));  // Exponential decay
    }
    std::discrete_distribution<size_t> dist(weights.begin(), weights.end());

    auto& chosen = candidates[dist(gen_)];
    is_vertical = chosen.is_vertical;
    return chosen.pos;
}

double BotSonnet::evaluatePlacementPosition(const Board::Position& pos,
                                                 size_t ship_size,
                                                 bool is_vertical) const {
    double score = 0.0;

    // Calculate ship endpoints
    int end_row = is_vertical ? pos.first + static_cast<int>(ship_size) - 1 : pos.first;
    int end_col = is_vertical ? pos.second : pos.second + static_cast<int>(ship_size) - 1;

    // -------------------------------------------------------------------------
    // Factor 1: Edge avoidance (edges are easier to find with probability hunting)
    // -------------------------------------------------------------------------
    double edge_penalty = 0.0;

    // Penalize if ship touches the border
    if (pos.first == 0 || end_row == static_cast<int>(Board::kBoardSizeRow) - 1) {
        edge_penalty -= 1.5;
    }
    if (pos.second == 0 || end_col == static_cast<int>(Board::kBoardSizeCol) - 1) {
        edge_penalty -= 1.5;
    }

    // Corner penalty (most obvious positions)
    bool at_corner = (pos.first == 0 || end_row == static_cast<int>(Board::kBoardSizeRow) - 1) &&
                     (pos.second == 0 || end_col == static_cast<int>(Board::kBoardSizeCol) - 1);
    if (at_corner) {
        edge_penalty -= 2.0;
    }

    // Bonus for being 1-3 cells away from edges (sweet spot)
    int min_row_dist = std::min(pos.first,
        static_cast<int>(Board::kBoardSizeRow) - 1 - end_row);
    int min_col_dist = std::min(pos.second,
        static_cast<int>(Board::kBoardSizeCol) - 1 - end_col);

    if (min_row_dist >= 1 && min_row_dist <= 3) edge_penalty += 0.5;
    if (min_col_dist >= 1 && min_col_dist <= 3) edge_penalty += 0.5;

    score += edge_penalty;

    // -------------------------------------------------------------------------
    // Factor 2: Distance from other ships (encourage spreading)
    // -------------------------------------------------------------------------
    if (!placed_ship_cells_.empty()) {
        double min_distance = std::numeric_limits<double>::max();
        double total_distance = 0.0;

        // Get all cells this ship would occupy
        std::vector<Board::Position> ship_cells;
        for (size_t i = 0; i < ship_size; ++i) {
            int r = is_vertical ? pos.first + static_cast<int>(i) : pos.first;
            int c = is_vertical ? pos.second : pos.second + static_cast<int>(i);
            ship_cells.push_back({r, c});
        }

        // Calculate distances to previously placed ships
        for (const auto& cell : ship_cells) {
            for (const auto& placed : placed_ship_cells_) {
                double dist = std::sqrt(
                    std::pow(cell.first - placed.first, 2) +
                    std::pow(cell.second - placed.second, 2));
                min_distance = std::min(min_distance, dist);
                total_distance += dist;
            }
        }

        // Reward being far from other ships
        score += min_distance * 0.8;
        score += (total_distance / static_cast<double>(placed_ship_cells_.size())) * 0.15;
    }

    // -------------------------------------------------------------------------
    // Factor 3: Avoid center (often first guess by opponents)
    // -------------------------------------------------------------------------
    double center_row = static_cast<double>(Board::kBoardSizeRow) / 2.0;
    double center_col = static_cast<double>(Board::kBoardSizeCol) / 2.0;

    double ship_center_row = pos.first + (is_vertical ? ship_size / 2.0 : 0.0);
    double ship_center_col = pos.second + (is_vertical ? 0.0 : ship_size / 2.0);

    double dist_from_center = std::sqrt(
        std::pow(ship_center_row - center_row, 2) +
        std::pow(ship_center_col - center_col, 2));

    // Optimal is 2-4 cells from center
    if (dist_from_center < 1.5) {
        score -= 1.0;  // Too central
    } else if (dist_from_center >= 2.0 && dist_from_center <= 4.0) {
        score += 0.5;  // Sweet spot
    }

    // -------------------------------------------------------------------------
    // Factor 4: Orientation variety (mix of horizontal and vertical)
    // -------------------------------------------------------------------------
    // Count existing orientations
    size_t placed_count = placed_ship_cells_.size();
    if (placed_count > 0 && ship_size > 1) {
        // Simple heuristic: alternate preference
        bool prefer_vertical = (placed_count / 2) % 2 == 0;
        if (is_vertical == prefer_vertical) {
            score += 0.3;
        }
    }

    // -------------------------------------------------------------------------
    // Factor 5: Randomness for unpredictability
    // -------------------------------------------------------------------------
    std::uniform_real_distribution<> noise(-0.3, 0.3);
    score += noise(gen_);

    return score;
}

// =============================================================================
// PROBABILITY-BASED SHOOTING
// =============================================================================

RequestId BotSonnet::makeShot() {
    Board::Position pos;

    if (mode_ == Mode::Target && !target_queue_.empty()) {
        // In target mode: prioritize based on hit chain orientation
        prioritizeTargetQueue();

        pos = target_queue_.front();
        target_queue_.pop_front();

        // Ensure target is still valid
        while (!isValidTarget(pos) && !target_queue_.empty()) {
            pos = target_queue_.front();
            target_queue_.pop_front();
        }

        if (!isValidTarget(pos)) {
            mode_ = Mode::Hunt;
            pos = findBestHuntTarget();
        }
    } else {
        // Hunt mode: use probability density
        mode_ = Mode::Hunt;
        pos = findBestHuntTarget();
    }

    tried_[pos.first][pos.second] = true;
    return action_interface_->makeShot(pos);
}

Board::Position BotSonnet::findBestHuntTarget() {
    auto prob_map = calculateProbabilityMap();

    // Find maximum probability
    double max_prob = -1.0;
    std::vector<Board::Position> best_positions;

    for (size_t r = 0; r < Board::kBoardSizeRow; ++r) {
        for (size_t c = 0; c < Board::kBoardSizeCol; ++c) {
            Board::Position pos{static_cast<int>(r), static_cast<int>(c)};

            if (!isValidTarget(pos)) continue;

            double prob = prob_map[r][c];

            if (prob > max_prob) {
                max_prob = prob;
                best_positions.clear();
                best_positions.push_back(pos);
            } else if (std::abs(prob - max_prob) < 0.001) {  // Essentially equal
                best_positions.push_back(pos);
            }
        }
    }

    // Fallback to random if no valid targets
    if (best_positions.empty()) {
        Board::Position pos;
        do {
            pos = randomPosition();
        } while (!isValidTarget(pos));
        return pos;
    }

    // Randomly select among best positions
    std::uniform_int_distribution<size_t> pick(0, best_positions.size() - 1);
    return best_positions[pick(gen_)];
}

std::vector<std::vector<double>> BotSonnet::calculateProbabilityMap() const {
    std::vector<std::vector<double>> prob_map(
        Board::kBoardSizeRow,
        std::vector<double>(Board::kBoardSizeCol, 0.0));

    // For each remaining ship, count how many valid placements cover each cell
    for (size_t ship_size : remaining_ship_sizes_) {
        if (ship_size == 0) continue;

        // Horizontal placements
        for (size_t r = 0; r < Board::kBoardSizeRow; ++r) {
            for (size_t c = 0; c <= Board::kBoardSizeCol - ship_size; ++c) {
                Board::Position start{static_cast<int>(r), static_cast<int>(c)};

                if (canShipFitAt(start, ship_size, false)) {  // horizontal
                    // This placement is valid - increment probability for covered cells
                    for (size_t i = 0; i < ship_size; ++i) {
                        prob_map[r][c + i] += 1.0;
                    }
                }
            }
        }

        // Vertical placements (only if ship_size > 1, otherwise already counted)
        if (ship_size > 1) {
            for (size_t r = 0; r <= Board::kBoardSizeRow - ship_size; ++r) {
                for (size_t c = 0; c < Board::kBoardSizeCol; ++c) {
                    Board::Position start{static_cast<int>(r), static_cast<int>(c)};

                    if (canShipFitAt(start, ship_size, true)) {  // vertical
                        for (size_t i = 0; i < ship_size; ++i) {
                            prob_map[r + i][c] += 1.0;
                        }
                    }
                }
            }
        }
    }

    // Apply parity optimization (only effective for ships size >= 2)
    size_t min_remaining_size = remaining_ship_sizes_.empty() ? 1 :
        *std::min_element(remaining_ship_sizes_.begin(), remaining_ship_sizes_.end());

    if (min_remaining_size >= 2) {
        // Use checkerboard pattern for efficiency
        for (size_t r = 0; r < Board::kBoardSizeRow; ++r) {
            for (size_t c = 0; c < Board::kBoardSizeCol; ++c) {
                // Checkerboard pattern: prioritize cells where (r+c) is even
                if ((r + c) % 2 == 0) {
                    prob_map[r][c] *= 1.1;  // 10% boost
                }
            }
        }
    }

    // Boost cells adjacent to isolated hits (increases chance of finding rest of ship)
    for (size_t r = 0; r < Board::kBoardSizeRow; ++r) {
        for (size_t c = 0; c < Board::kBoardSizeCol; ++c) {
            if (cell_states_[r][c] == CellState::Hit) {
                // Boost adjacent cells
                static const int dr[] = {-1, 1, 0, 0};
                static const int dc[] = {0, 0, -1, 1};

                for (int i = 0; i < 4; ++i) {
                    int nr = static_cast<int>(r) + dr[i];
                    int nc = static_cast<int>(c) + dc[i];

                    if (nr >= 0 && nr < static_cast<int>(Board::kBoardSizeRow) &&
                        nc >= 0 && nc < static_cast<int>(Board::kBoardSizeCol) &&
                        cell_states_[nr][nc] == CellState::Unknown) {
                        prob_map[nr][nc] *= 2.0;  // Strong boost for cells near hits
                    }
                }
            }
        }
    }

    return prob_map;
}

bool BotSonnet::canShipFitAt(const Board::Position& start,
                                  size_t size, bool is_vertical) const {
    for (size_t i = 0; i < size; ++i) {
        int r = is_vertical ? start.first + static_cast<int>(i) : start.first;
        int c = is_vertical ? start.second : start.second + static_cast<int>(i);

        // Check bounds
        if (r < 0 || c < 0 ||
            static_cast<size_t>(r) >= Board::kBoardSizeRow ||
            static_cast<size_t>(c) >= Board::kBoardSizeCol) {
            return false;
        }

        // Check if cell was a miss (can't place ship through a miss)
        if (cell_states_[r][c] == CellState::Miss) {
            return false;
        }

        // Note: Hits are okay - ship could extend through known hit cells
    }
    return true;
}

// =============================================================================
// INTELLIGENT TARGETING MODE
// =============================================================================

void BotSonnet::prioritizeTargetQueue() {
    if (target_queue_.size() <= 1) return;

    // Remove invalid targets first
    target_queue_.erase(
        std::remove_if(target_queue_.begin(), target_queue_.end(),
            [this](const Board::Position& p) { return !isValidTarget(p); }),
        target_queue_.end());

    if (target_queue_.size() <= 1) return;

    // If we have 2+ hits, we know the ship's orientation
    auto [is_horizontal, is_vertical] = detectHitOrientation();

    if (is_horizontal || is_vertical) {
        filterTargetQueueByOrientation();
    }

    // Sort remaining targets by likelihood
    std::sort(target_queue_.begin(), target_queue_.end(),
        [this](const Board::Position& a, const Board::Position& b) {
            // Prefer cells that extend the hit chain at endpoints
            if (current_hit_chain_.empty()) return false;

            auto [is_horiz, is_vert] = detectHitOrientation();

            auto get_endpoint_priority = [&](const Board::Position& pos) -> int {
                if (current_hit_chain_.size() < 2) {
                    // Just count adjacency to any hit
                    int adj_count = 0;
                    for (const auto& hit : current_hit_chain_) {
                        if (std::abs(pos.first - hit.first) +
                            std::abs(pos.second - hit.second) == 1) {
                            adj_count++;
                        }
                    }
                    return adj_count;
                }

                // Find endpoints of the chain
                auto [min_row_it, max_row_it] = std::minmax_element(
                    current_hit_chain_.begin(), current_hit_chain_.end(),
                    [](const auto& p1, const auto& p2) { return p1.first < p2.first; });
                auto [min_col_it, max_col_it] = std::minmax_element(
                    current_hit_chain_.begin(), current_hit_chain_.end(),
                    [](const auto& p1, const auto& p2) { return p1.second < p2.second; });

                // Check if pos extends from an endpoint
                if (is_horiz) {
                    if (pos.first == min_col_it->first) {
                        if (pos.second == min_col_it->second - 1 ||
                            pos.second == max_col_it->second + 1) {
                            return 10;  // High priority - extends the line
                        }
                    }
                } else if (is_vert) {
                    if (pos.second == min_row_it->second) {
                        if (pos.first == min_row_it->first - 1 ||
                            pos.first == max_row_it->first + 1) {
                            return 10;  // High priority - extends the line
                        }
                    }
                }
                return 0;
            };

            return get_endpoint_priority(a) > get_endpoint_priority(b);
        });
}

std::pair<bool, bool> BotSonnet::detectHitOrientation() const {
    if (current_hit_chain_.size() < 2) {
        return {false, false};
    }

    bool same_row = true;
    bool same_col = true;

    for (size_t i = 1; i < current_hit_chain_.size(); ++i) {
        if (current_hit_chain_[i].first != current_hit_chain_[0].first) {
            same_row = false;
        }
        if (current_hit_chain_[i].second != current_hit_chain_[0].second) {
            same_col = false;
        }
    }

    return {same_row, same_col};  // {horizontal, vertical}
}

void BotSonnet::filterTargetQueueByOrientation() {
    auto [is_horizontal, is_vertical] = detectHitOrientation();

    if (!is_horizontal && !is_vertical) return;
    if (current_hit_chain_.empty()) return;

    // Find the extent of current hit chain
    auto [min_row_it, max_row_it] = std::minmax_element(
        current_hit_chain_.begin(), current_hit_chain_.end(),
        [](const auto& p1, const auto& p2) { return p1.first < p2.first; });
    auto [min_col_it, max_col_it] = std::minmax_element(
        current_hit_chain_.begin(), current_hit_chain_.end(),
        [](const auto& p1, const auto& p2) { return p1.second < p2.second; });

    std::deque<Board::Position> filtered;

    for (const auto& target : target_queue_) {
        bool keep = false;

        if (is_horizontal) {
            // Ship is horizontal - only keep targets in the same row
            if (target.first == current_hit_chain_[0].first) {
                // Check if it's at an endpoint
                if (target.second == min_col_it->second - 1 ||
                    target.second == max_col_it->second + 1) {
                    keep = true;
                }
            }
        }

        if (is_vertical) {
            // Ship is vertical - only keep targets in the same column
            if (target.second == current_hit_chain_[0].second) {
                // Check if it's at an endpoint
                if (target.first == min_row_it->first - 1 ||
                    target.first == max_row_it->first + 1) {
                    keep = true;
                }
            }
        }

        if (keep) {
            filtered.push_back(target);
        }
    }

    // Only apply filter if we still have targets
    if (!filtered.empty()) {
        target_queue_ = std::move(filtered);
    }
}

// =============================================================================
// EVENT HANDLERS
// =============================================================================

void BotSonnet::onPlayerShotResult(const Board::Position& position,
                                        const bool is_hit,
                                        const bool is_ship_sunk) {
    // Update cell state tracking
    cell_states_[position.first][position.second] =
        is_hit ? CellState::Hit : CellState::Miss;

    if (is_ship_sunk) {
        onShipSunk();
        return;
    }

    if (is_hit) {
        onHit(position);
    }
}

void BotSonnet::onHit(const Board::Position& pos) {
    mode_ = Mode::Target;
    current_hit_chain_.push_back(pos);
    enqueueNeighbors(pos);
}

void BotSonnet::onShipSunk() {
    // Determine sunk ship size
    size_t sunk_size = current_hit_chain_.size();

    // Find and remove the matching ship size from remaining ships
    auto it = std::find(remaining_ship_sizes_.begin(),
                        remaining_ship_sizes_.end(),
                        sunk_size);

    if (it != remaining_ship_sizes_.end()) {
        remaining_ship_sizes_.erase(it);
        LOG_V("Ship of size {} sunk. Ships remaining", sunk_size, remaining_ship_sizes_.size());
    } else {
        // This might happen if we hit cells from multiple ships
        // Try to find the best match
        LOG_W("Could not find exact match for sunk ship of size {}", sunk_size);

        // Find closest size >= sunk_size
        auto closest = std::find_if(remaining_ship_sizes_.begin(),
                                    remaining_ship_sizes_.end(),
                                    [sunk_size](size_t s) { return s >= sunk_size; });
        if (closest != remaining_ship_sizes_.end()) {
            remaining_ship_sizes_.erase(closest);
        }
    }

    // Mark cells around the sunk ship as effectively "miss" since ships can't be adjacent
    // (if your game rules have this constraint)
    for (const auto& hit_pos : current_hit_chain_) {
        static const int dr[] = {-1, -1, -1, 0, 0, 1, 1, 1};
        static const int dc[] = {-1, 0, 1, -1, 1, -1, 0, 1};

        for (int i = 0; i < 8; ++i) {
            int nr = hit_pos.first + dr[i];
            int nc = hit_pos.second + dc[i];

            if (nr >= 0 && nr < static_cast<int>(Board::kBoardSizeRow) &&
                nc >= 0 && nc < static_cast<int>(Board::kBoardSizeCol)) {
                // Mark diagonal and adjacent cells as "tried" if unknown
                if (cell_states_[nr][nc] == CellState::Unknown) {
                    tried_[nr][nc] = true;
                    // Don't change cell_state - keep it Unknown for probability calc
                    // But it won't be selected since tried_ is true
                }
            }
        }
    }

    // Reset targeting state
    mode_ = Mode::Hunt;
    target_queue_.clear();
    current_hit_chain_.clear();
}

void BotSonnet::enqueueNeighbors(const Board::Position& pos) {
    static const int dr[] = {-1, 1, 0, 0};
    static const int dc[] = {0, 0, -1, 1};

    for (int i = 0; i < 4; ++i) {
        Board::Position next{pos.first + dr[i], pos.second + dc[i]};

        if (isValidTarget(next)) {
            // Avoid duplicates in queue
            bool already_queued = std::find_if(target_queue_.begin(),
                target_queue_.end(),
                [&next](const Board::Position& p) {
                    return p.first == next.first && p.second == next.second;
                }) != target_queue_.end();

            if (!already_queued) {
                target_queue_.push_back(next);
            }
        }
    }
}

// =============================================================================
// UTILITY METHODS
// =============================================================================

Board::Position BotSonnet::randomPosition() const {
    std::uniform_int_distribution<int> row(0, static_cast<int>(Board::kBoardSizeRow) - 1);
    std::uniform_int_distribution<int> col(0, static_cast<int>(Board::kBoardSizeCol) - 1);
    return {row(gen_), col(gen_)};
}

bool BotSonnet::isValidTarget(const Board::Position& pos) const {
    if (pos.first < 0 || pos.second < 0) return false;
    if (static_cast<size_t>(pos.first) >= Board::kBoardSizeRow ||
        static_cast<size_t>(pos.second) >= Board::kBoardSizeCol)
        return false;
    return !tried_[pos.first][pos.second] &&
           Board::Board::is_valid_shot(oponent_board_, pos);
}
