/*
    This file is generated by ChatGPT 5.2 for compare between different AI models and stategy to play BattleShipGame
*/
#include "bot_gpt.h"
#include "board.h"
#include "log.h"

#include <algorithm>
#include <limits>
#include <queue>

BotGpt::BotGpt(std::shared_ptr<GameSession::IGamePlayerAction> action_interface,
                             const PlayerType player_type)
    : PlayerBotBase(action_interface, player_type),
      gen_(rd_()) {
    enemy_.assign(Board::kBoardSizeRow,
                  std::vector<Cell>(Board::kBoardSizeCol, Cell::Unknown));
    LOG_I("Create a bot generated by ChatGpt");
    initRemainingShipsFromBoardRules();
}

void BotGpt::initRemainingShipsFromBoardRules() {
    remaining_lengths_.clear();
    for (int t = 0; t < static_cast<int>(Board::ShipType::NumberOfShips); ++t) {
        auto type = static_cast<Board::ShipType>(t);
        const size_t count = Board::get_max_ship_count(type);
        const int len = static_cast<int>(Board::get_ship_size(type));
        for (size_t i = 0; i < count; ++i) remaining_lengths_.push_back(len);
    }
    // optional: keep sorted (helps debugging)
    std::sort(remaining_lengths_.begin(), remaining_lengths_.end());
}

// ---------------------------
// Smarter ship placement
// ---------------------------
int BotGpt::edgeDist(int r, int c) {
    const int top = r;
    const int left = c;
    const int bottom = static_cast<int>(Board::kBoardSizeRow) - 1 - r;
    const int right  = static_cast<int>(Board::kBoardSizeCol) - 1 - c;
    return std::min({top, left, bottom, right}); // 0 at edge
}

int BotGpt::shipPlacementScore(Board::Position pos, bool horizontal, size_t L) const {
    // Lower score = preferred
    int score = 0;

    for (size_t k = 0; k < L; ++k) {
        int r = pos.first  + (horizontal ? 0 : static_cast<int>(k));
        int c = pos.second + (horizontal ? static_cast<int>(k) : 0);

        score += 2 * edgeDist(r, c); // prefer edges/corners

        // Small “spread” penalty: avoid being close to existing ships
        // (even if your placement rules already prevent adjacency, this still helps spacing)
        for (int dr = -2; dr <= 2; ++dr) {
            for (int dc = -2; dc <= 2; ++dc) {
                int rr = r + dr, cc = c + dc;
                if (rr < 0 || cc < 0) continue;
                if (rr >= static_cast<int>(Board::kBoardSizeRow) ||
                    cc >= static_cast<int>(Board::kBoardSizeCol)) continue;

                if (board_[rr][cc].field == Board::BoardFieldStatus::Ship) {
                    score += 3;
                }
            }
        }
    }
    return score;
}

RequestId BotGpt::placeShip(const Board::ShipType ship_type) {
    // Detect start of a new game:
    // - engine cleared our local board_ (no ships)
    // - but we previously placed ships in an earlier game
    const bool board_empty_now = !ownBoardHasAnyShips();
    if (!new_game_initialized_ || (ships_placed_in_current_game_ > 0 && board_empty_now)) {
        resetForNewGame();
    }

    std::uniform_int_distribution<> row(0, Board::kBoardSizeRow - 1);
    std::uniform_int_distribution<> col(0, Board::kBoardSizeCol - 1);
    std::uniform_int_distribution<> rot(0, 1);

    const size_t L = Board::get_ship_size(ship_type);

    constexpr int kTries = 500;
    bool found = false;
    int bestScore = std::numeric_limits<int>::max();
    Board::Position bestPos{0, 0};
    bool bestHorizontal = true;

    for (int t = 0; t < kTries; ++t) {
        Board::Position pos{row(gen_), col(gen_)};
        bool horizontal = (rot(gen_) != 0);

        const bool is_vertical = !horizontal;
        if (!Board::Board::is_possible_to_place_ship(board_, pos, ship_type, is_vertical))
            continue;

        int score = shipPlacementScore(pos, horizontal, L);
        if (score < bestScore) {
            bestScore = score;
            bestPos = pos;
            bestHorizontal = horizontal;
            found = true;
        }
    }

    if (!found) {
        // fallback: original random loop
        Board::Position pos;
        bool horizontal;
        do {
            pos = {row(gen_), col(gen_)};
            horizontal = (rot(gen_) != 0);
        } while (!Board::Board::is_possible_to_place_ship(board_, pos, ship_type, !horizontal));
        return action_interface_->placeShip(ship_type, pos, horizontal);
    }
    ++ships_placed_in_current_game_;

    return action_interface_->placeShip(ship_type, bestPos, bestHorizontal);
}

// ---------------------------
// Probability shooting
// ---------------------------
bool BotGpt::isValidTarget(const Board::Position& pos) const {
    const int r = pos.first, c = pos.second;
    if (r < 0 || c < 0) return false;
    if (r >= static_cast<int>(Board::kBoardSizeRow) ||
        c >= static_cast<int>(Board::kBoardSizeCol))
        return false;

    if (enemy_[r][c] != Cell::Unknown) return false;
    return Board::Board::is_valid_shot(oponent_board_, pos);
}

Board::Position BotGpt::randomPosition() {
    std::uniform_int_distribution<> row(0, Board::kBoardSizeRow - 1);
    std::uniform_int_distribution<> col(0, Board::kBoardSizeCol - 1);
    return {row(gen_), col(gen_)};
}

std::vector<std::vector<bool>> BotGpt::visitedMask() const {
    return std::vector<std::vector<bool>>(Board::kBoardSizeRow,
                                          std::vector<bool>(Board::kBoardSizeCol, false));
}

std::vector<Board::Position> BotGpt::collectHitClusterFrom(const Board::Position& start) const {
    std::vector<Board::Position> cluster;
    if (start.first < 0) return cluster;

    auto vis = visitedMask();
    std::queue<Board::Position> q;

    auto pushIfHit = [&](int r, int c) {
        if (r < 0 || c < 0) return;
        if (r >= static_cast<int>(Board::kBoardSizeRow) ||
            c >= static_cast<int>(Board::kBoardSizeCol))
            return;
        if (vis[r][c]) return;
        if (enemy_[r][c] != Cell::Hit) return;
        vis[r][c] = true;
        q.push({r, c});
    };

    pushIfHit(start.first, start.second);
    while (!q.empty()) {
        auto p = q.front(); q.pop();
        cluster.push_back(p);

        pushIfHit(p.first - 1, p.second);
        pushIfHit(p.first + 1, p.second);
        pushIfHit(p.first, p.second - 1);
        pushIfHit(p.first, p.second + 1);
    }

    return cluster;
}

std::vector<std::vector<Board::Position>> BotGpt::getAllHitClusters() const {
    auto vis = visitedMask();
    std::vector<std::vector<Board::Position>> clusters;

    for (int r = 0; r < static_cast<int>(Board::kBoardSizeRow); ++r) {
        for (int c = 0; c < static_cast<int>(Board::kBoardSizeCol); ++c) {
            if (vis[r][c]) continue;
            if (enemy_[r][c] != Cell::Hit) continue;

            // BFS
            std::vector<Board::Position> cluster;
            std::queue<Board::Position> q;
            vis[r][c] = true;
            q.push({r, c});

            while (!q.empty()) {
                auto p = q.front(); q.pop();
                cluster.push_back(p);

                const int dr[4] = {-1, 1, 0, 0};
                const int dc[4] = {0, 0, -1, 1};
                for (int i = 0; i < 4; ++i) {
                    int rr = p.first + dr[i], cc = p.second + dc[i];
                    if (rr < 0 || cc < 0) continue;
                    if (rr >= static_cast<int>(Board::kBoardSizeRow) ||
                        cc >= static_cast<int>(Board::kBoardSizeCol))
                        continue;
                    if (vis[rr][cc]) continue;
                    if (enemy_[rr][cc] != Cell::Hit) continue;
                    vis[rr][cc] = true;
                    q.push({rr, cc});
                }
            }

            clusters.push_back(std::move(cluster));
        }
    }
    return clusters;
}

std::vector<Board::Position> BotGpt::chooseTargetCluster() const {
    auto clusters = getAllHitClusters();
    if (clusters.empty()) return {};

    // Choose the largest cluster (most likely to be close to sinking)
    auto it = std::max_element(clusters.begin(), clusters.end(),
                              [](auto& a, auto& b) { return a.size() < b.size(); });
    return *it;
}

bool BotGpt::placementConsistent(int r, int c, bool horizontal, int L,
                                        const std::vector<Board::Position>& targetCluster) const {
    // Placement cells cannot include Miss/Sunk
    // Also: if we are targeting a cluster, placement must include all its cells
    // and must not include Hit cells outside that cluster.
    auto inPlacement = [&](int rr, int cc) {
        if (horizontal) return (rr == r && cc >= c && cc < c + L);
        return (cc == c && rr >= r && rr < r + L);
    };

    // quick bounds are ensured by loops in heatmap creation

    for (int k = 0; k < L; ++k) {
        int rr = r + (horizontal ? 0 : k);
        int cc = c + (horizontal ? k : 0);

        Cell cell = enemy_[rr][cc];
        if (cell == Cell::Miss || cell == Cell::Sunk) return false;
    }

    if (!targetCluster.empty()) {
        // must include all cells from target cluster
        for (const auto& h : targetCluster) {
            if (!inPlacement(h.first, h.second)) return false;
        }

        // must NOT include any other hits outside the cluster
        // (prevents combining two separate hit clusters into one impossible ship)
        for (int rr = 0; rr < static_cast<int>(Board::kBoardSizeRow); ++rr) {
            for (int cc = 0; cc < static_cast<int>(Board::kBoardSizeCol); ++cc) {
                if (enemy_[rr][cc] != Cell::Hit) continue;
                bool isInTarget = std::find(targetCluster.begin(), targetCluster.end(),
                                            Board::Position{rr, cc}) != targetCluster.end();
                if (!isInTarget && inPlacement(rr, cc)) return false;
            }
        }
    }

    return true;
}

Board::Position BotGpt::bestHeatmapShot() {
    const int R = static_cast<int>(Board::kBoardSizeRow);
    const int C = static_cast<int>(Board::kBoardSizeCol);

    std::vector<std::vector<int>> heat(R, std::vector<int>(C, 0));

    const auto targetCluster = chooseTargetCluster();

    // If we have hits, ignore pure-hunt placements (no-hit placements)
    // by only counting placements consistent with the cluster constraint.

    for (int L : remaining_lengths_) {
        // horizontal
        for (int r = 0; r < R; ++r) {
            for (int c = 0; c + L - 1 < C; ++c) {
                if (!placementConsistent(r, c, true, L, targetCluster)) continue;

                // If targeting, ensure placement actually covers the cluster
                // (already guaranteed when targetCluster non-empty)
                for (int k = 0; k < L; ++k) {
                    if (enemy_[r][c + k] == Cell::Unknown)
                        heat[r][c + k] += 1;
                }
            }
        }
        // vertical
        for (int r = 0; r + L - 1 < R; ++r) {
            for (int c = 0; c < C; ++c) {
                if (!placementConsistent(r, c, false, L, targetCluster)) continue;

                for (int k = 0; k < L; ++k) {
                    if (enemy_[r + k][c] == Cell::Unknown)
                        heat[r + k][c] += 1;
                }
            }
        }
    }

    int best = -1;
    std::vector<Board::Position> bestCells;

    for (int r = 0; r < R; ++r) {
        for (int c = 0; c < C; ++c) {
            Board::Position p{r, c};
            if (!isValidTarget(p)) continue;
            if (heat[r][c] > best) {
                best = heat[r][c];
                bestCells.clear();
                bestCells.push_back(p);
            } else if (heat[r][c] == best) {
                bestCells.push_back(p);
            }
        }
    }

    if (bestCells.empty()) {
        if (auto any = findAnyValidTarget(); any.has_value())
            return *any;

        LOG_E("BotGpt: No valid targets left, but game not finished. "
            "enemy_ Unknown cells: {}", 
            std::count_if(enemy_.begin(), enemy_.end(), [](auto& row){
                return std::count(row.begin(), row.end(), Cell::Unknown);
            }));
        throw std::runtime_error("BotGpt: no valid shots left");
    }

    std::uniform_int_distribution<> pick(0, static_cast<int>(bestCells.size()) - 1);
    return bestCells[pick(gen_)];
}

RequestId BotGpt::makeShot() {
    Board::Position pos = bestHeatmapShot();
    if (!isValidTarget(pos)) {
        LOG_E("BotGpt produced invalid shot ({}, {})", pos.first, pos.second);
        throw std::runtime_error("BotGpt invalid shot");
    }
    return action_interface_->makeShot(pos);
}

// ---------------------------
// Updating knowledge
// ---------------------------
void BotGpt::removeSunkLength(int len) {
    auto it = std::find(remaining_lengths_.begin(), remaining_lengths_.end(), len);
    if (it != remaining_lengths_.end()) remaining_lengths_.erase(it);
}

void BotGpt::markWaterAroundSunkCluster(const std::vector<Board::Position>& cluster) {
    // Classic rule: ships cannot touch; after sinking a ship, all adjacent cells are water.
    for (const auto& p : cluster) {
        for (int dr = -1; dr <= 1; ++dr) {
            for (int dc = -1; dc <= 1; ++dc) {
                if (dr == 0 && dc == 0) continue;
                int rr = p.first + dr;
                int cc = p.second + dc;
                if (rr < 0 || cc < 0) continue;
                if (rr >= static_cast<int>(Board::kBoardSizeRow) ||
                    cc >= static_cast<int>(Board::kBoardSizeCol))
                    continue;

                if (enemy_[rr][cc] == Cell::Unknown)
                    enemy_[rr][cc] = Cell::Miss;
            }
        }
    }
}

void BotGpt::onPlayerShotResult(const Board::Position& pos,
                                const bool is_hit,
                                const bool is_ship_sunk) {
    const bool hit = is_hit || is_ship_sunk; // ShipDestroyed must imply a hit

    if (!hit) {
        enemy_[pos.first][pos.second] = Cell::Miss;
        return;
    }

    enemy_[pos.first][pos.second] = Cell::Hit;

    if (is_ship_sunk) {
        auto cluster = collectHitClusterFrom(pos);
        for (const auto& h : cluster) enemy_[h.first][h.second] = Cell::Sunk;
        removeSunkLength(static_cast<int>(cluster.size()));
        markWaterAroundSunkCluster(cluster);
    }
}

std::optional<Board::Position> BotGpt::findAnyValidTarget() const {
    for (int r = 0; r < static_cast<int>(Board::kBoardSizeRow); ++r) {
        for (int c = 0; c < static_cast<int>(Board::kBoardSizeCol); ++c) {
            Board::Position p{r, c};
            if (isValidTarget(p)) return p;
        }
    }
    return std::nullopt;
}

bool BotGpt::ownBoardHasAnyShips() const noexcept {
    for (size_t r = 0; r < Board::kBoardSizeRow; ++r) {
        for (size_t c = 0; c < Board::kBoardSizeCol; ++c) {
            if (board_[r][c].field == Board::BoardFieldStatus::Ship) {
                return true;
            }
        }
    }
    return false;
}

void BotGpt::resetForNewGame() {
    LOG_I("BotGpt resetForNewGame()");

    // reset shooting knowledge
    enemy_.assign(Board::kBoardSizeRow,
                  std::vector<Cell>(Board::kBoardSizeCol, Cell::Unknown));

    initRemainingShipsFromBoardRules();

    // IMPORTANT: if you keep using oponent_board_ in isValidTarget, reset it too
    // (depends on PlayerBotBase, but typically these are protected BoardType)
    // This makes Board::is_valid_shot(...) not block all shots in the next game.
    for (auto& row : oponent_board_) row.fill({});
    for (auto& row : board_) row.fill({}); // local placement helper board

    ships_placed_in_current_game_ = 0;
    new_game_initialized_ = true;
}
